name: Build ARM Docker Image

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/arm/v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/arm/v7
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/kahoot-clone:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/kahoot-clone:armv7
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/kahoot-clone:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/kahoot-clone:buildcache,mode=max
